// <auto-generated />
using iD_Develops.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace iD_Develops.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718074113_AddSchedulingProviderIntegrations")]
    partial class AddSchedulingProviderIntegrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
